# ================================= Flask Server ===============================
FROM python:3-alpine as flask

WORKDIR /app
COPY ["Pipfile", "shell_scripts/auto_pipenv.sh", "./"]
RUN pip install pipenv

COPY . .

RUN pipenv lock
RUN pipenv install --system --deploy

EXPOSE 5000
# RUN pipenv run flask db init
# RUN pipenv run flask db migrate
# RUN pipenv run flask db upgrade

ENTRYPOINT [ "pipenv", "run", "flask", "run" , "--host=0.0.0.0"]
