version: "3.6"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - ./dev.db:/tmp/dev.db

services:
  flask:
    build:
      context: .
      target: flask
      dockerfile: Dockerfile.flask
    image: "brewpi-flask"
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      # - ./dev.db:/tmp/dev.db
  react:
    build:
      context: .
      target: react
      dockerfile: Dockerfile.react
    image: "brewpi-react"
    tty: true
    links:
      - flask
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
  redis:
    image: "redis:alpine"
volumes:
  static-build:
  dev-db:
